steps:
# build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
# Push image to registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
# Deploy contianer to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: 
  - run
  - --filename=gke.yaml
  - --image='gcr.io/$PROJECT_ID/gcpdevops'
  - --location=northamerica-northeast1-a
  - --cluster=gap-devops-project
  - --namespace=gcp-devops-prod

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE