name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List Repository Structure
        run: |
          pwd
          ls -la
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests with pytest
        run: |
          pip install pytest
          cd ${{ github.workspace }}
          pytest --maxfail=1 --disable-warnings -q

      - name: Type check with Mypy
        run: |
          pip install mypy
          mypy .

  build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKEHUB_USERNAME}}/python-flask:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: ${{secrets.DOCKEHUB_USERNAME}}/python-flask:${{ github.sha }}

      - name: Login to Docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: | 
          docker push ${{secrets.DOCKEHUB_USERNAME}}/python-flask:${{ github.sha }}
      